FROM webhippie/python:latest-arm64v8

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.label-schema.name="Yamllint" \
  org.label-schema.vendor="Thomas Boerger" \
  org.label-schema.schema-version="1.0"

ENTRYPOINT [""]

ENV PY_COLORS=1

RUN apk update && \
  apk upgrade && \
  apk add yamllint && \
  rm -rf /var/cache/apk/*
